import { useState, useCallback, useMemo, useRef } from 'react';
import { motion } from 'framer-motion';
import { useCourseStore } from '../store/courseStore';
import { useApiStore } from '../store/apiStore';
import { useUiStore } from '../store/uiStore';
import { streamMessage } from '../services/claude/streaming';
import { MODELS } from '../services/claude/client';
import { buildChapterPrompt, buildChapterUserPrompt } from '../prompts/chapter';
import { buildPracticeQuizPrompt, buildPracticeQuizUserPrompt } from '../prompts/practiceQuiz';
import { buildInClassQuizPrompt, buildInClassQuizUserPrompt } from '../prompts/inClassQuiz';
import {
  buildLearningObjectivesPrompt,
  buildLearningObjectivesUserPrompt,
  parseCurriculumMapResponse,
} from '../prompts/learningObjectives';
import {
  buildOutcomesPage,
  buildOutcomesCsv,
  buildOutcomesTableFragment,
  hashSyllabus,
} from '../templates/outcomesTableTemplate';
import { CodexButton as Button } from '../components/codex';
import type { InClassQuizQuestion } from '../types/course';
import { friendlyError } from '../utils/errors';
import { buildProjectFile } from '../utils/projectFile';
import { ThemePicker } from '../components/export/ThemePicker';
import type { ChapterThemeId } from '../themes';
import { DEFAULT_CHAPTER_THEME_ID, renderChapterHtml } from '../themes';
import { extractHtml } from '../utils/format';

function downloadFile(content: string | Blob, filename: string, type = 'text/html') {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function sanitizeFilename(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** Short index file shipped at the top of each class bundle so an instructor
 *  unzipping it sees exactly what's inside and how to use each file. */
function buildClassReadme(
  chapter: import('../types/course').GeneratedChapter,
  courseTitle: string,
  chapterNum: number,
): string {
  const lines: string[] = [];
  lines.push(`${courseTitle}`);
  lines.push(`Class ${String(chapterNum).padStart(2, '0')} — ${chapter.title}`);
  lines.push('='.repeat(64));
  lines.push('');
  lines.push('Generated by ClassBuild · classbuild.app');
  lines.push('');
  lines.push('CONTENTS');
  lines.push('-'.repeat(64));
  lines.push('reading.html              The chapter reading, themed for offline viewing.');
  if (chapter.practiceQuizData) {
    lines.push('practice-quiz.html        Self-paced practice quiz (twelve questions).');
  }
  if (chapter.inClassQuizData && chapter.inClassQuizData.length > 0) {
    lines.push('in-class-quiz-pack.zip    Five shuffled .docx versions + answer key.');
  }
  if (chapter.weeklyChallengeData) {
    lines.push('weekly-challenge.html     Mastery challenge — open in a browser.');
    lines.push('weekly-challenge-scorm.zip  SCORM 2004 package — upload to Canvas / Moodle / Blackboard.');
  }
  if (chapter.slidesJson) {
    lines.push('slides.pptx               12–14-slide lecture deck (or slides.json if no OpenAI key).');
  }
  if (chapter.audioUrl || chapter.audioDataUri) {
    lines.push('audiobook.mp3             Class audiobook narrated through ElevenLabs.');
  }
  if (chapter.audioTranscript) {
    lines.push('audio-transcript.txt      Plain-text transcript adapted for spoken delivery.');
  }
  if ((chapter.discussionData?.length || 0) + (chapter.activityData?.length || 0) > 0) {
    lines.push('teaching-pack.docx        Conversation starters + in-class activities + facilitation guides.');
  }
  lines.push('');
  lines.push('Everything is offline — no internet needed to use any of the files.');
  return lines.join('\n');
}

export function ExportPage() {
  const { syllabus, chapters, researchDossiers, addChapter, updateChapter, setSlideImage, setup, updateSetup, curriculumMap, setCurriculumMap } = useCourseStore();
  const currentThemeId = (setup.themeId as ChapterThemeId | undefined) ?? DEFAULT_CHAPTER_THEME_ID;
  const { claudeApiKey, openaiApiKey } = useApiStore();
  const { isGenerating, setIsGenerating, setError, error } = useUiStore();
  const [generatingChapter, setGeneratingChapter] = useState<number | null>(null);
  const [isPublishing, setIsPublishing] = useState(false);
  const [isGeneratingOutcomes, setIsGeneratingOutcomes] = useState(false);
  const [outcomesError, setOutcomesError] = useState<string | null>(null);
  const [outcomesStreamChars, setOutcomesStreamChars] = useState(0);
  const outcomesStreamRef = useRef('');

  // --- Download handlers ---

  const handleDownloadChapter = useCallback((chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter) return;
    downloadFile(
      renderChapterHtml(chapter.htmlContent, setup.themeId, chapter.title),
      `chapter-${chapterNum}-${sanitizeFilename(chapter.title)}.html`,
    );
  }, [chapters, setup.themeId]);

  const handleDownloadQuiz = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter?.practiceQuizData || !syllabus) return;
    try {
      const { buildQuizHtml } = await import('../templates/quizTemplate');
      const html = buildQuizHtml(`${chapter.title} — Practice Quiz`, chapter.practiceQuizData, syllabus.courseTitle, setup.themeId);
      downloadFile(html, `quiz-${chapterNum}-${sanitizeFilename(chapter.title)}.html`);
    } catch {
      downloadFile(chapter.practiceQuizData, `quiz-${chapterNum}-${sanitizeFilename(chapter.title)}.txt`, 'text/plain');
    }
  }, [chapters, syllabus]);

  const handleDownloadSlides = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter?.slidesJson || !syllabus) return;
    if (!openaiApiKey) {
      setError('Add an OpenAI API key in Setup to render the slide images.');
      return;
    }
    // Guard: only one slide render in flight across the app.
    const { slidesRender } = useUiStore.getState();
    if (slidesRender) {
      setError(
        slidesRender.chapterNum === chapterNum
          ? 'This deck is already rendering. Wait for it to finish.'
          : `Another deck (Class ${slidesRender.chapterNum}) is rendering. Wait for it to finish.`,
      );
      return;
    }
    useUiStore.getState().setSlidesRender({
      chapterNum,
      current: 0,
      total: chapter.slidesJson.length,
      phase: 'rendering',
    });
    try {
      const { generatePptx } = await import('../services/export/pptxExporter');
      const { blob } = await generatePptx(
        chapter.slidesJson,
        syllabus.courseTitle,
        chapter.title,
        setup.themeId,
        openaiApiKey,
        {
          imageQuality: 'high',
          imageSize: '3840x2160',
          onProgress: (current, total, phase) =>
            useUiStore.getState().setSlidesRender({
              chapterNum,
              current,
              total,
              phase,
            }),
          onSlideRendered: (i, dataUri) => setSlideImage(chapterNum, i, dataUri),
          preRendered: Object.fromEntries(
            chapter.slidesJson
              .map((s, i) => (s.imageDataUri ? [i, s.imageDataUri] : null))
              .filter((x): x is [number, string] => x !== null),
          ),
        },
      );
      downloadFile(blob, `slides-${chapterNum}-${sanitizeFilename(chapter.title)}.pptx`);
    } catch (err) {
      setError(friendlyError(err, 'Slides export failed.'));
      downloadFile(JSON.stringify(chapter.slidesJson, null, 2), `slides-${chapterNum}-${sanitizeFilename(chapter.title)}.json`, 'application/json');
    } finally {
      useUiStore.getState().setSlidesRender(null);
    }
  }, [chapters, syllabus, setup.themeId, openaiApiKey, setSlideImage, setError]);

  const handleDownloadInClassQuiz = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter?.inClassQuizData || !syllabus) return;
    try {
      const { generateQuizDocPackage } = await import('../services/export/quizDocExporter');
      const blob = await generateQuizDocPackage(chapter.inClassQuizData, syllabus.courseTitle, chapter.title);
      downloadFile(blob, `quiz-pack-${chapterNum}-${sanitizeFilename(chapter.title)}.zip`, 'application/zip');
    } catch {
      downloadFile(JSON.stringify(chapter.inClassQuizData, null, 2), `quiz-${chapterNum}-${sanitizeFilename(chapter.title)}.json`, 'application/json');
    }
  }, [chapters, syllabus]);

  const handleDownloadWeeklyChallenge = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter?.weeklyChallengeData || !syllabus) return;
    try {
      const { buildWeeklyChallengeHtml } = await import('../templates/weeklyChallengeTemplate');
      const html = buildWeeklyChallengeHtml(`Week ${chapterNum} Challenge — ${chapter.title}`, chapter.weeklyChallengeData, syllabus.courseTitle, setup.themeId);
      downloadFile(html, `weekly-challenge-${chapterNum}-${sanitizeFilename(chapter.title)}.html`);
    } catch {
      downloadFile(JSON.stringify(chapter.weeklyChallengeData, null, 2), `weekly-challenge-${chapterNum}-${sanitizeFilename(chapter.title)}.json`, 'application/json');
    }
  }, [chapters, syllabus, setup.themeId]);

  const handleDownloadWeeklyChallengeSCORM = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!syllabus) return;
    if (!chapter?.weeklyChallengeData?.questions?.length) {
      setError('No weekly challenge to package yet — generate the mastery challenge for this chapter first, then export the SCORM package.');
      return;
    }
    try {
      const { buildWeeklyChallengeHtml } = await import('../templates/weeklyChallengeTemplate');
      const { default: JSZip } = await import('jszip');
      const html = buildWeeklyChallengeHtml(`Week ${chapterNum} Challenge — ${chapter.title}`, chapter.weeklyChallengeData, syllabus.courseTitle, setup.themeId);
      const launchFile = `weekly-challenge-${chapterNum}.html`;
      const title = `Week ${chapterNum} Challenge — ${chapter.title}`;
      const escXml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
      const manifest = `<?xml version="1.0" encoding="UTF-8"?>\n<manifest identifier="classbuild-scorm-pkg" version="1.0" xmlns="http://www.imsglobal.org/xsd/imscp_v1p1" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3" xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3" xmlns:adlnav="http://www.adlnet.org/xsd/adlnav_v1p3" xmlns:imsss="http://www.imsglobal.org/xsd/imsss" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd http://www.adlnet.org/xsd/adlnav_v1p3 adlnav_v1p3.xsd http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd"><metadata><schema>ADL SCORM</schema><schemaversion>2004 4th Edition</schemaversion></metadata><organizations default="org-1"><organization identifier="org-1"><title>${escXml(title)}</title><item identifier="item-1" identifierref="res-1"><title>${escXml(title)}</title></item></organization></organizations><resources><resource identifier="res-1" type="webcontent" adlcp:scormType="sco" href="${escXml(launchFile)}"><file href="${escXml(launchFile)}" /></resource></resources></manifest>`;
      const zip = new JSZip();
      zip.file('imsmanifest.xml', manifest);
      zip.file(launchFile, html);
      const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
      downloadFile(blob, `weekly-challenge-${chapterNum}-${sanitizeFilename(chapter.title)}-scorm.zip`, 'application/zip');
    } catch (err) {
      setError(friendlyError(err, 'SCORM export failed.'));
    }
  }, [chapters, syllabus, setup.themeId, setError]);

  const handleDownloadAudio = useCallback((chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter) return;
    const audioSrc = chapter.audioUrl ?? chapter.audioDataUri;
    if (!audioSrc) return;
    const a = document.createElement('a');
    a.href = audioSrc;
    a.download = `audio-${chapterNum}-${sanitizeFilename(chapter.title)}.mp3`;
    a.click();
  }, [chapters]);

  const handleDownloadTeachingResources = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find(c => c.number === chapterNum);
    if (!chapter || !syllabus) return;
    const discussions = chapter.discussionData || [];
    const activities = chapter.activityData || [];
    const details = chapter.activityDetails || {};
    if (discussions.length === 0 && activities.length === 0) return;

    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');
    const children: InstanceType<typeof Paragraph>[] = [];

    // Title
    children.push(new Paragraph({
      children: [new TextRun({ text: `Teaching Resources — ${chapter.title}`, bold: true, size: 32 })],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: syllabus.courseTitle, italics: true, color: '666666', size: 22 })],
      spacing: { after: 400 },
    }));

    // Discussion starters
    if (discussions.length > 0) {
      children.push(new Paragraph({
        children: [new TextRun({ text: 'Conversation Starters', bold: true, size: 28 })],
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 200 },
      }));
      children.push(new Paragraph({
        children: [new TextRun({ text: 'Display these on a slide as students arrive.', italics: true, color: '888888', size: 20 })],
        spacing: { after: 200 },
      }));
      discussions.forEach((d, i) => {
        children.push(new Paragraph({
          children: [
            new TextRun({ text: `${i + 1}. `, bold: true, size: 22 }),
            new TextRun({ text: `[${d.hook}] `, bold: true, color: '8b5cf6', size: 22 }),
            new TextRun({ text: d.prompt, size: 22 }),
          ],
          spacing: { after: 150 },
        }));
      });
    }

    // Activities
    if (activities.length > 0) {
      children.push(new Paragraph({
        children: [new TextRun({ text: 'In-Class Activities', bold: true, size: 28 })],
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }));
      activities.forEach((a, i) => {
        children.push(new Paragraph({
          children: [
            new TextRun({ text: `${a.title}`, bold: true, size: 24 }),
            new TextRun({ text: `  (${a.duration})`, color: '888888', size: 20 }),
          ],
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 300, after: 100 },
        }));
        children.push(new Paragraph({
          children: [new TextRun({ text: a.description, size: 22 })],
          spacing: { after: 100 },
        }));
        children.push(new Paragraph({
          children: [
            new TextRun({ text: 'Materials: ', bold: true, size: 20 }),
            new TextRun({ text: a.materials, size: 20 }),
          ],
          spacing: { after: 50 },
        }));
        children.push(new Paragraph({
          children: [
            new TextRun({ text: 'Learning Goal: ', bold: true, size: 20 }),
            new TextRun({ text: a.learningGoal, size: 20 }),
          ],
          spacing: { after: 50 },
        }));
        children.push(new Paragraph({
          children: [
            new TextRun({ text: 'Scaling: ', bold: true, size: 20 }),
            new TextRun({ text: a.scalingNotes, size: 20 }),
          ],
          spacing: { after: 100 },
        }));

        // Expanded guide if available
        const detail = details[i];
        if (detail) {
          children.push(new Paragraph({
            children: [new TextRun({ text: 'Step-by-Step Guide', bold: true, size: 22, underline: {} })],
            spacing: { before: 150, after: 100 },
          }));
          detail.steps.forEach(s => {
            children.push(new Paragraph({
              children: [
                new TextRun({ text: `[${s.timing}] `, bold: true, size: 20 }),
                new TextRun({ text: s.instruction, size: 20 }),
              ],
              spacing: { after: 30 },
              indent: { left: 360 },
            }));
            if (s.studentAction) {
              children.push(new Paragraph({
                children: [new TextRun({ text: `Students: ${s.studentAction}`, italics: true, color: '666666', size: 18 })],
                indent: { left: 720 },
                spacing: { after: 80 },
              }));
            }
          });
          if (detail.facilitationTips.length > 0) {
            children.push(new Paragraph({
              children: [new TextRun({ text: 'Facilitation Tips', bold: true, size: 20 })],
              spacing: { before: 100, after: 50 },
            }));
            detail.facilitationTips.forEach(t => {
              children.push(new Paragraph({
                children: [new TextRun({ text: `• ${t}`, size: 20 })],
                indent: { left: 360 },
                spacing: { after: 30 },
              }));
            });
          }
          if (detail.commonPitfalls.length > 0) {
            children.push(new Paragraph({
              children: [new TextRun({ text: 'Common Pitfalls', bold: true, size: 20 })],
              spacing: { before: 100, after: 50 },
            }));
            detail.commonPitfalls.forEach(p => {
              children.push(new Paragraph({
                children: [new TextRun({ text: `• ${p}`, size: 20 })],
                indent: { left: 360 },
                spacing: { after: 30 },
              }));
            });
          }
          children.push(new Paragraph({
            children: [
              new TextRun({ text: 'Debrief: ', bold: true, size: 20 }),
              new TextRun({ text: detail.debriefGuide, size: 20 }),
            ],
            spacing: { before: 100, after: 100 },
          }));
        }
      });
    }

    // Footer
    children.push(new Paragraph({
      children: [new TextRun({ text: `Generated by ClassBuild`, italics: true, color: '999999', size: 18 })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    }));

    const doc = new Document({ sections: [{ children }] });
    const blob = await Packer.toBlob(doc);
    downloadFile(blob, `teaching-resources-${chapterNum}-${sanitizeFilename(chapter.title)}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  }, [chapters, syllabus]);

  const buildCurriculumMapCsv = useCallback(() => {
    if (!curriculumMap || !syllabus) return null;
    return buildOutcomesCsv(curriculumMap, syllabus);
  }, [curriculumMap, syllabus]);

  const handleDownloadOutcomesCsv = useCallback(() => {
    const csv = buildCurriculumMapCsv();
    if (!csv || !syllabus) return;
    const name = sanitizeFilename(syllabus.courseTitle) || 'course';
    downloadFile(csv, `${name}-learning-outcomes.csv`, 'text/csv');
  }, [buildCurriculumMapCsv, syllabus]);

  const handleDownloadOutcomesHtml = useCallback(() => {
    if (!curriculumMap || !syllabus) return;
    const html = buildOutcomesPage(curriculumMap, syllabus, setup.themeId);
    const name = sanitizeFilename(syllabus.courseTitle) || 'course';
    downloadFile(html, `${name}-learning-outcomes.html`);
  }, [curriculumMap, syllabus, setup.themeId]);

  // ── Learning outcomes: generation flow ──────────────────────────────

  const currentSyllabusHash = useMemo(
    () => (syllabus ? hashSyllabus(syllabus) : null),
    [syllabus],
  );
  const outcomesStale =
    !!curriculumMap &&
    !!currentSyllabusHash &&
    !!curriculumMap.syllabusHash &&
    curriculumMap.syllabusHash !== currentSyllabusHash;

  const generateLearningOutcomes = useCallback(async () => {
    if (!syllabus || !claudeApiKey || isGeneratingOutcomes) return;
    setIsGeneratingOutcomes(true);
    setOutcomesError(null);
    outcomesStreamRef.current = '';
    setOutcomesStreamChars(0);
    try {
      const text = await streamMessage(
        {
          apiKey: claudeApiKey,
          model: MODELS.haiku,
          system: buildLearningObjectivesPrompt(),
          messages: [
            { role: 'user', content: buildLearningObjectivesUserPrompt(syllabus) },
          ],
          maxTokens: 6000,
        },
        {
          onText: (delta) => {
            outcomesStreamRef.current += delta;
            setOutcomesStreamChars(outcomesStreamRef.current.length);
          },
        },
      );
      const map = parseCurriculumMapResponse(text);
      if (!map) {
        setOutcomesError(
          'The model returned an unparseable response. Try regenerating.',
        );
        return;
      }
      map.syllabusHash = currentSyllabusHash ?? undefined;
      setCurriculumMap(map);
    } catch (err) {
      setOutcomesError(friendlyError(err, 'Learning outcomes generation failed.'));
    } finally {
      setIsGeneratingOutcomes(false);
    }
  }, [
    syllabus,
    claudeApiKey,
    isGeneratingOutcomes,
    currentSyllabusHash,
    setCurriculumMap,
  ]);

  // --- Generate a single chapter from export page ---

  const generateSingleChapter = useCallback(async (chapterNum: number) => {
    if (!syllabus || isGenerating) return;
    const ch = syllabus.chapters.find(c => c.number === chapterNum);
    if (!ch) return;

    setIsGenerating(true);
    setGeneratingChapter(chapterNum);

    try {
      const dossier = researchDossiers.find(d => d.chapterNumber === chapterNum);
      const researchSources = dossier?.sources.map(s => ({
        title: s.title, authors: s.authors, year: s.year,
        summary: s.summary, url: s.url, doi: s.doi,
      }));

      // Generate chapter
      const fullText = await streamMessage(
        {
          apiKey: claudeApiKey,
          model: MODELS.opus,
          system: buildChapterPrompt(setup.themeId),
          messages: [{ role: 'user', content: buildChapterUserPrompt(syllabus.courseTitle, ch, setup.chapterLength, { educationLevel: setup.educationLevel, priorKnowledge: setup.priorKnowledge, learnerNotes: setup.learnerNotes }, researchSources) }],
          thinkingBudget: 'high',
          maxTokens: 16000,
        },
        { onError: (err) => setError(err.message) }
      );

      const html = extractHtml(fullText);
      addChapter({ number: chapterNum, title: ch.title, htmlContent: html });

      // Generate practice quiz
      try {
        const quizText = await streamMessage(
          {
            apiKey: claudeApiKey,
            model: MODELS.opus,
            system: buildPracticeQuizPrompt(),
            messages: [{ role: 'user', content: buildPracticeQuizUserPrompt(ch.title, ch.narrative, ch.keyConcepts, html.slice(0, 3000)) }],
            thinkingBudget: 'high',
            maxTokens: 8000,
          },
          { onError: (err) => setError(err.message) }
        );
        updateChapter(chapterNum, { practiceQuizData: quizText });
      } catch { /* continue */ }

      // Generate in-class quiz
      try {
        const inClassText = await streamMessage(
          {
            apiKey: claudeApiKey,
            model: MODELS.opus,
            system: buildInClassQuizPrompt(),
            messages: [{ role: 'user', content: buildInClassQuizUserPrompt(ch.title, ch.narrative, ch.keyConcepts, html.slice(0, 3000)) }],
            thinkingBudget: 'high',
            maxTokens: 8000,
          },
          { onError: (err) => setError(err.message) }
        );
        try {
          let jsonStr = inClassText;
          const codeMatch = jsonStr.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
          if (codeMatch) jsonStr = codeMatch[1];
          const fb = jsonStr.indexOf('[');
          const lb = jsonStr.lastIndexOf(']');
          if (fb !== -1 && lb !== -1) jsonStr = jsonStr.slice(fb, lb + 1);
          jsonStr = jsonStr.replace(/,\s*([}\]])/g, '$1');
          for (let attempt = 0; attempt < 10; attempt++) {
            try {
              const parsed = JSON.parse(jsonStr) as InClassQuizQuestion[];
              updateChapter(chapterNum, { inClassQuizData: parsed });
              break;
            } catch (e) {
              if (e instanceof SyntaxError) {
                const posMatch = e.message.match(/position (\d+)/);
                if (posMatch) {
                  const pos = parseInt(posMatch[1]);
                  if (pos > 0 && pos < jsonStr.length && jsonStr[pos] === '"') {
                    jsonStr = jsonStr.slice(0, pos) + '\\"' + jsonStr.slice(pos + 1);
                    continue;
                  }
                }
              }
              break;
            }
          }
        } catch { /* parse failed */ }
      } catch { /* continue */ }
    } catch (err) {
      setError(`Chapter ${chapterNum}: ${friendlyError(err, 'generation failed.')}`);
    } finally {
      setIsGenerating(false);
      setGeneratingChapter(null);
    }
  }, [syllabus, chapters, claudeApiKey, researchDossiers, setup.chapterLength, addChapter, updateChapter, isGenerating, setIsGenerating, setError]);

  // --- Per-class bundle ---
  //
  // Single-class ZIP with everything generated for that one chapter: reading,
  // quizzes, slides (rendered PPTX if cached, JSON fallback otherwise), audio
  // MP3 (fetched from the blob URL while the page is still open), teaching
  // pack DOCX, transcript text. Smaller than the full-course ZIP, faster, and
  // sufficient for an instructor who just wants today's class.

  const handleDownloadClassBundle = useCallback(async (chapterNum: number) => {
    const chapter = chapters.find((c) => c.number === chapterNum);
    if (!chapter || !syllabus) return;

    const { default: JSZip } = await import('jszip');
    const { saveAs } = await import('file-saver');

    const chapterName = sanitizeFilename(chapter.title);
    const folderName = `class-${String(chapterNum).padStart(2, '0')}-${chapterName}`;
    const zip = new JSZip();
    const root = zip.folder(folderName);
    if (!root) return;

    // 1. Reading
    root.file(
      `reading.html`,
      renderChapterHtml(chapter.htmlContent, setup.themeId, chapter.title),
    );

    // 2. Practice quiz
    if (chapter.practiceQuizData) {
      try {
        const { buildQuizHtml } = await import('../templates/quizTemplate');
        root.file(
          `practice-quiz.html`,
          buildQuizHtml(
            `${chapter.title} — Practice Quiz`,
            chapter.practiceQuizData,
            syllabus.courseTitle,
            setup.themeId,
          ),
        );
      } catch {
        root.file(`practice-quiz.txt`, chapter.practiceQuizData);
      }
    }

    // 3. In-class quiz pack (5 shuffled versions + answer key)
    if (chapter.inClassQuizData && chapter.inClassQuizData.length > 0) {
      try {
        const { generateQuizDocPackage } = await import('../services/export/quizDocExporter');
        const quizZip = await generateQuizDocPackage(
          chapter.inClassQuizData,
          syllabus.courseTitle,
          chapter.title,
        );
        root.file(`in-class-quiz-pack.zip`, quizZip);
      } catch {
        root.file(`in-class-quiz.json`, JSON.stringify(chapter.inClassQuizData, null, 2));
      }
    }

    // 4. Weekly challenge — themed HTML + SCORM bundle for LMS upload
    if (chapter.weeklyChallengeData) {
      try {
        const { buildWeeklyChallengeHtml } = await import('../templates/weeklyChallengeTemplate');
        const challengeHtml = buildWeeklyChallengeHtml(
          `Week ${chapterNum} Challenge — ${chapter.title}`,
          chapter.weeklyChallengeData,
          syllabus.courseTitle,
          setup.themeId,
        );
        root.file(`weekly-challenge.html`, challengeHtml);

        // SCORM wrapper for direct LMS import.
        const launchFile = `weekly-challenge.html`;
        const escXml = (s: string) =>
          s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
        const title = `Week ${chapterNum} Challenge — ${chapter.title}`;
        const manifest = `<?xml version="1.0" encoding="UTF-8"?>\n<manifest identifier="classbuild-scorm-pkg" version="1.0" xmlns="http://www.imsglobal.org/xsd/imscp_v1p1" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><metadata><schema>ADL SCORM</schema><schemaversion>2004 4th Edition</schemaversion></metadata><organizations default="org-1"><organization identifier="org-1"><title>${escXml(title)}</title><item identifier="item-1" identifierref="res-1"><title>${escXml(title)}</title></item></organization></organizations><resources><resource identifier="res-1" type="webcontent" adlcp:scormType="sco" href="${escXml(launchFile)}"><file href="${escXml(launchFile)}" /></resource></resources></manifest>`;
        const scormZip = new JSZip();
        scormZip.file('imsmanifest.xml', manifest);
        scormZip.file(launchFile, challengeHtml);
        const scormBlob = await scormZip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
        root.file(`weekly-challenge-scorm.zip`, scormBlob);
      } catch {
        root.file(`weekly-challenge.json`, JSON.stringify(chapter.weeklyChallengeData, null, 2));
      }
    }

    // 5. Slides — render PPTX if OpenAI key + slides exist; otherwise JSON
    if (chapter.slidesJson && openaiApiKey) {
      try {
        useUiStore.getState().setSlidesRender({
          chapterNum: chapter.number,
          current: 0,
          total: chapter.slidesJson.length,
          phase: 'rendering',
        });
        const { generatePptx } = await import('../services/export/pptxExporter');
        const { blob: pptxBlob } = await generatePptx(
          chapter.slidesJson,
          syllabus.courseTitle,
          chapter.title,
          setup.themeId,
          openaiApiKey,
          {
            imageQuality: 'high',
            imageSize: '3840x2160',
            onProgress: (current, total, phase) =>
              useUiStore.getState().setSlidesRender({
                chapterNum: chapter.number,
                current,
                total,
                phase,
              }),
            onSlideRendered: (i, dataUri) => setSlideImage(chapter.number, i, dataUri),
            preRendered: Object.fromEntries(
              chapter.slidesJson
                .map((s, i) => (s.imageDataUri ? [i, s.imageDataUri] : null))
                .filter((x): x is [number, string] => x !== null),
            ),
          },
        );
        root.file(`slides.pptx`, pptxBlob);
      } catch {
        root.file(`slides.json`, JSON.stringify(chapter.slidesJson, null, 2));
      } finally {
        useUiStore.getState().setSlidesRender(null);
      }
    } else if (chapter.slidesJson) {
      root.file(`slides.json`, JSON.stringify(chapter.slidesJson, null, 2));
    }

    // 6. Audio — fetch the blob URL while the page is still open (it dies on
    //    reload, so this is the only chance to capture it into the ZIP).
    const chapterAudio = chapter.audioUrl ?? chapter.audioDataUri;
    if (chapterAudio) {
      try {
        const audioBlob = await fetch(chapterAudio).then((r) => r.blob());
        root.file(`audiobook.mp3`, audioBlob);
      } catch {
        /* blob fetch failed — skip */
      }
    }
    if (chapter.audioTranscript) {
      root.file(`audio-transcript.txt`, chapter.audioTranscript);
    }

    // 7. Teaching pack DOCX (discussion + activities)
    const discussions = chapter.discussionData || [];
    const activities = chapter.activityData || [];
    if (discussions.length > 0 || activities.length > 0) {
      try {
        // Re-use the same code path as the per-chip Teaching download, but
        // capture the generated DOCX blob instead of triggering a download.
        await (async () => {
          const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx');
          const details = chapter.activityDetails || {};
          const children: InstanceType<typeof Paragraph>[] = [];
          children.push(new Paragraph({
            children: [new TextRun({ text: `Teaching Resources — ${chapter.title}`, bold: true, size: 32 })],
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 200 },
          }));
          children.push(new Paragraph({
            children: [new TextRun({ text: syllabus.courseTitle, italics: true, color: '666666', size: 22 })],
            spacing: { after: 400 },
          }));
          if (discussions.length > 0) {
            children.push(new Paragraph({
              children: [new TextRun({ text: 'Conversation Starters', bold: true, size: 28 })],
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 200 },
            }));
            discussions.forEach((d, i) => {
              children.push(new Paragraph({
                children: [
                  new TextRun({ text: `${i + 1}. `, bold: true, size: 22 }),
                  new TextRun({ text: `[${d.hook}] `, bold: true, color: '8b5cf6', size: 22 }),
                  new TextRun({ text: d.prompt, size: 22 }),
                ],
                spacing: { after: 150 },
              }));
            });
          }
          if (activities.length > 0) {
            children.push(new Paragraph({
              children: [new TextRun({ text: 'In-Class Activities', bold: true, size: 28 })],
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 400, after: 200 },
            }));
            activities.forEach((a, i) => {
              children.push(new Paragraph({
                children: [
                  new TextRun({ text: `${a.title}`, bold: true, size: 24 }),
                  new TextRun({ text: `  (${a.duration})`, color: '888888', size: 20 }),
                ],
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 300, after: 100 },
              }));
              children.push(new Paragraph({ children: [new TextRun({ text: a.description, size: 22 })], spacing: { after: 100 } }));
              children.push(new Paragraph({ children: [new TextRun({ text: 'Materials: ', bold: true, size: 20 }), new TextRun({ text: a.materials, size: 20 })], spacing: { after: 50 } }));
              children.push(new Paragraph({ children: [new TextRun({ text: 'Learning Goal: ', bold: true, size: 20 }), new TextRun({ text: a.learningGoal, size: 20 })], spacing: { after: 50 } }));
              children.push(new Paragraph({ children: [new TextRun({ text: 'Scaling: ', bold: true, size: 20 }), new TextRun({ text: a.scalingNotes, size: 20 })], spacing: { after: 100 } }));
              const detail = details[i];
              if (detail) {
                children.push(new Paragraph({ children: [new TextRun({ text: 'Step-by-Step Guide', bold: true, size: 22, underline: {} })], spacing: { before: 150, after: 100 } }));
                detail.steps.forEach((s) => {
                  children.push(new Paragraph({ children: [new TextRun({ text: `[${s.timing}] `, bold: true, size: 20 }), new TextRun({ text: s.instruction, size: 20 })], spacing: { after: 50 } }));
                  if (s.studentAction) {
                    children.push(new Paragraph({ children: [new TextRun({ text: `→ Students: ${s.studentAction}`, italics: true, color: '666666', size: 20 })], spacing: { after: 50 } }));
                  }
                });
              }
            });
          }
          const doc = new Document({ sections: [{ children }] });
          const docxBlob = await Packer.toBlob(doc);
          root.file(`teaching-pack.docx`, docxBlob);
        })();
      } catch {
        /* docx build failed — skip */
      }
    }

    // 8. README — short index file so anyone unzipping understands what's inside.
    const readme = buildClassReadme(chapter, syllabus.courseTitle, chapterNum);
    root.file(`README.txt`, readme);

    const blob = await zip.generateAsync({ type: 'blob' });
    saveAs(blob, `${folderName}.zip`);
  }, [chapters, syllabus, setup.themeId, openaiApiKey, setSlideImage]);

  // --- Download All ---

  const handleDownloadAll = useCallback(async () => {
    const { default: JSZip } = await import('jszip');
    const { saveAs } = await import('file-saver');

    const courseName = sanitizeFilename(syllabus?.courseTitle || 'course');
    const zip = new JSZip();
    const courseFolder = zip.folder(courseName);

    for (const chapter of chapters) {
      const chapterName = sanitizeFilename(chapter.title);

      courseFolder?.file(
        `chapter-${chapter.number}-${chapterName}.html`,
        renderChapterHtml(chapter.htmlContent, setup.themeId, chapter.title),
      );

      if (chapter.practiceQuizData && syllabus) {
        try {
          const { buildQuizHtml } = await import('../templates/quizTemplate');
          const quizHtml = buildQuizHtml(`${chapter.title} — Practice Quiz`, chapter.practiceQuizData, syllabus.courseTitle, setup.themeId);
          courseFolder?.file(`quiz-${chapter.number}-${chapterName}.html`, quizHtml);
        } catch {
          courseFolder?.file(`quiz-${chapter.number}-${chapterName}.txt`, chapter.practiceQuizData);
        }
      }

      if (chapter.inClassQuizData && chapter.inClassQuizData.length > 0 && syllabus) {
        try {
          const { generateQuizDocPackage } = await import('../services/export/quizDocExporter');
          const quizZip = await generateQuizDocPackage(chapter.inClassQuizData, syllabus.courseTitle, chapter.title);
          courseFolder?.file(`in-class-quiz-${chapter.number}-${chapterName}.zip`, quizZip);
        } catch {
          courseFolder?.file(`in-class-quiz-${chapter.number}-${chapterName}.json`, JSON.stringify(chapter.inClassQuizData, null, 2));
        }
      }

      if (chapter.weeklyChallengeData && syllabus) {
        try {
          const { buildWeeklyChallengeHtml } = await import('../templates/weeklyChallengeTemplate');
          const challengeHtml = buildWeeklyChallengeHtml(`Week ${chapter.number} Challenge — ${chapter.title}`, chapter.weeklyChallengeData, syllabus.courseTitle, setup.themeId);
          courseFolder?.file(`weekly-challenge-${chapter.number}-${chapterName}.html`, challengeHtml);
        } catch {
          courseFolder?.file(`weekly-challenge-${chapter.number}-${chapterName}.json`, JSON.stringify(chapter.weeklyChallengeData, null, 2));
        }
      }

      if (chapter.slidesJson && syllabus && openaiApiKey) {
        // For the Download-All flow we render each chapter's deck in turn,
        // gated by the same global slidesRender mutex so a previously-
        // initiated single-chapter render can't collide with this loop.
        try {
          useUiStore.getState().setSlidesRender({
            chapterNum: chapter.number,
            current: 0,
            total: chapter.slidesJson.length,
            phase: 'rendering',
          });
          const { generatePptx } = await import('../services/export/pptxExporter');
          const { blob: pptxBlob } = await generatePptx(
            chapter.slidesJson,
            syllabus.courseTitle,
            chapter.title,
            setup.themeId,
            openaiApiKey,
            {
              imageQuality: 'high',
              imageSize: '3840x2160',
              onProgress: (current, total, phase) =>
                useUiStore.getState().setSlidesRender({
                  chapterNum: chapter.number,
                  current,
                  total,
                  phase,
                }),
              onSlideRendered: (i, dataUri) =>
                setSlideImage(chapter.number, i, dataUri),
              preRendered: Object.fromEntries(
                chapter.slidesJson
                  .map((s, i) => (s.imageDataUri ? [i, s.imageDataUri] : null))
                  .filter((x): x is [number, string] => x !== null),
              ),
            },
          );
          courseFolder?.file(`slides-${chapter.number}-${chapterName}.pptx`, pptxBlob);
        } catch {
          courseFolder?.file(`slides-${chapter.number}-${chapterName}.json`, JSON.stringify(chapter.slidesJson, null, 2));
        } finally {
          useUiStore.getState().setSlidesRender(null);
        }
      } else if (chapter.slidesJson) {
        // No OpenAI key — fall back to JSON only.
        courseFolder?.file(`slides-${chapter.number}-${chapterName}.json`, JSON.stringify(chapter.slidesJson, null, 2));
      }

      // Audio blob URLs can't be included in ZIP (lost on reload), skip audio in ZIP
    }

    // Learning outcomes — both CSV (re-import) and themed HTML (read).
    const csv = buildCurriculumMapCsv();
    if (csv) {
      courseFolder?.file('learning-outcomes.csv', csv);
    }
    if (curriculumMap && syllabus) {
      const outcomesHtml = buildOutcomesPage(curriculumMap, syllabus, setup.themeId);
      courseFolder?.file('learning-outcomes.html', outcomesHtml);
    }

    const blob = await zip.generateAsync({ type: 'blob' });
    saveAs(blob, `${courseName}.zip`);
  }, [syllabus, chapters, setup.themeId, buildCurriculumMapCsv, curriculumMap]);

  const handlePublish = useCallback(async () => {
    if (!syllabus || chapters.length === 0) return;
    setIsPublishing(true);
    try {
      const { assemblePublishSite } = await import('../services/export/publishExporter');
      const blob = await assemblePublishSite(syllabus, chapters, setup.themeId);
      const courseName = sanitizeFilename(syllabus.courseTitle) || 'course';
      downloadFile(blob, `${courseName}-site.zip`, 'application/zip');
    } catch (err) {
      setError(friendlyError(err, 'Publish failed.'));
    } finally {
      setIsPublishing(false);
    }
  }, [syllabus, chapters, setup.themeId, setError]);

  // --- Project file (backup/restore) ---
  //
  // A portable snapshot of the whole course — re-opened from the landing
  // page's "Restore a project file" affordance. API keys are never included.

  const handleDownloadProjectFile = useCallback(() => {
    const name = sanitizeFilename(syllabus?.courseTitle ?? '') || 'course';
    downloadFile(buildProjectFile(), `${name}.classbuild.json`, 'application/json');
  }, [syllabus]);

  // --- Derived data ---

  if (!syllabus) {
    return (
      <div
        style={{
          maxWidth: 720,
          margin: '0 auto',
          padding: '80px 24px',
          fontFamily: 'var(--font-cb-serif)',
          color: 'var(--cb-text-muted)',
          textAlign: 'center',
          fontStyle: 'italic',
          fontSize: 18,
          lineHeight: 1.5,
        }}
      >
        No course in progress. Start one from <a style={{ color: 'var(--cb-accent-emphasis)' }} href="/setup">Setup</a>.
      </div>
    );
  }

  const totalChapters = syllabus.chapters.length;
  const readyCount = chapters.length;
  const allReady = readyCount === totalChapters;

  // Count downloadable files per chapter and totals
  const FILES_PER_CHAPTER = 7; // HTML, practice quiz, in-class quiz, weekly challenge, slides, audio, teaching resources
  const totalPossibleFiles = totalChapters * FILES_PER_CHAPTER;

  function countFiles(c: typeof chapters[number]): number {
    let n = 1; // chapter HTML always
    if (c.practiceQuizData) n++;
    if (c.inClassQuizData && c.inClassQuizData.length > 0) n++;
    if (c.weeklyChallengeData) n++;
    if (c.slidesJson) n++;
    if (c.audioUrl || c.audioDataUri) n++;
    if ((c.discussionData && c.discussionData.length > 0) || (c.activityData && c.activityData.length > 0)) n++;
    return n;
  }

  const fileCount = chapters.reduce((acc, c) => acc + countFiles(c), 0);

  const progressPct = totalPossibleFiles === 0 ? 0 : (fileCount / totalPossibleFiles) * 100;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      style={{
        fontFamily: 'var(--font-cb-serif)',
        color: 'var(--cb-text-default)',
        padding: '32px 0 56px',
      }}
    >
      <div style={{ maxWidth: 1180, margin: '0 auto' }}>
        {/* ── EDITORIAL HEADER ─────────────────────────────────── */}
        <header style={{ marginBottom: 32 }}>
          <div
            className="cb-sc"
            style={{
              fontSize: 13,
              letterSpacing: '0.16em',
              color: 'var(--cb-accent-emphasis)',
            }}
          >
            Stage 5 · Export
          </div>
          <h1
            className="cb-italic"
            style={{
              margin: '8px 0 10px',
              fontSize: 46,
              fontWeight: 500,
              lineHeight: 1.05,
              letterSpacing: '-0.01em',
              fontVariationSettings: '"opsz" 36',
              color: 'var(--cb-text-default)',
              maxWidth: '20ch',
            }}
          >
            {syllabus.courseTitle}
          </h1>
          <p
            className="cb-italic"
            style={{
              margin: '0 0 24px',
              fontSize: 18,
              lineHeight: 1.5,
              color: 'var(--cb-text-muted)',
              maxWidth: 640,
            }}
          >
            {allReady
              ? `${totalChapters} chapters drafted · ${fileCount} of ${totalPossibleFiles} artifacts ready.`
              : `${readyCount} of ${totalChapters} chapters drafted · ${fileCount} of ${totalPossibleFiles} artifacts ready.`}
          </p>

          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'baseline' }}>
            <Button
              variant="primary"
              size="lg"
              onClick={handlePublish}
              disabled={chapters.length === 0 || isPublishing}
            >
              {isPublishing ? 'Publishing…' : 'Publish · course site (.zip) →'}
            </Button>
            <Button
              variant="ghost"
              size="lg"
              onClick={handleDownloadAll}
              disabled={chapters.length === 0 || isGenerating}
            >
              {allReady
                ? 'Download all · ZIP ↓'
                : `Download ${readyCount} of ${totalChapters} · ZIP ↓`}
            </Button>
            <Button
              variant="ghost"
              size="lg"
              onClick={handleDownloadProjectFile}
              title="Re-open this course on any machine. Keys are not included."
            >
              Project file ↓
            </Button>
          </div>
        </header>

        {/* ── ERROR BANNER ─────────────────────────────────────── */}
        {error && (
          <div
            style={{
              marginBottom: 24,
              padding: '12px 18px',
              borderLeft: '3px solid var(--cb-status-danger)',
              background: 'var(--cb-status-danger-bg)',
              color: 'var(--cb-status-danger)',
              fontStyle: 'italic',
              fontSize: 14,
              lineHeight: 1.5,
            }}
          >
            {error}
          </div>
        )}

        {/* ── COURSE STYLE PICKER ─────────────────────────────── */}
        <ThemePicker
          selectedId={currentThemeId}
          onSelect={(id) => updateSetup({ themeId: id })}
        />

        {/* ── PROGRESS STRIP ──────────────────────────────────── */}
        <section style={{ marginBottom: 28 }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'baseline',
              justifyContent: 'space-between',
              marginBottom: 10,
            }}
          >
            <span
              className="cb-sc"
              style={{
                fontSize: 13,
                letterSpacing: '0.14em',
                color: 'var(--cb-text-muted)',
              }}
            >
              Course progress
            </span>
            <span
              className="cb-mono"
              style={{
                fontSize: 12.5,
                color: fileCount === totalPossibleFiles
                  ? 'var(--cb-status-success)'
                  : 'var(--cb-text-muted)',
                letterSpacing: '0.04em',
              }}
            >
              {fileCount === totalPossibleFiles
                ? '✓ all artifacts ready'
                : `${fileCount} of ${totalPossibleFiles} artifacts`}
            </span>
          </div>
          <div
            role="progressbar"
            aria-valuenow={Math.round(progressPct)}
            aria-valuemin={0}
            aria-valuemax={100}
            style={{
              height: 2,
              background: 'var(--cb-border-default)',
              position: 'relative',
              overflow: 'hidden',
            }}
          >
            <div
              style={{
                position: 'absolute',
                left: 0,
                top: 0,
                bottom: 0,
                width: `${progressPct}%`,
                background: 'var(--cb-accent-emphasis)',
                transition: 'width 320ms cubic-bezier(0.32,0.04,0.32,1)',
              }}
            />
          </div>
        </section>

        {/* ── CHAPTER INDEX ───────────────────────────────────── */}
        <section style={{ marginBottom: 48 }}>
          <div
            className="cb-sc"
            style={{
              fontSize: 13,
              letterSpacing: '0.14em',
              color: 'var(--cb-text-muted)',
              borderBottom: '0.5px solid var(--cb-border-rule)',
              paddingBottom: 10,
              marginBottom: 4,
            }}
          >
            Chapters
          </div>

          {syllabus.chapters.map((ch) => {
            const generated = chapters.find((c) => c.number === ch.number);
            const isCurrentlyGenerating = generatingChapter === ch.number;

            if (!generated) {
              return (
                <ChapterRowEmpty
                  key={ch.number}
                  number={ch.number}
                  title={ch.title}
                  isGenerating={isGenerating}
                  isCurrent={isCurrentlyGenerating}
                  onGenerate={() => generateSingleChapter(ch.number)}
                />
              );
            }

            const chapterFileCount = countFiles(generated);
            const isComplete = chapterFileCount === FILES_PER_CHAPTER;

            const artifacts: Array<{ label: string; onClick: () => void }> = [
              { label: 'reading', onClick: () => handleDownloadChapter(ch.number) },
            ];
            if (generated.practiceQuizData) {
              artifacts.push({
                label: 'practice quiz',
                onClick: () => handleDownloadQuiz(ch.number),
              });
            }
            if (generated.inClassQuizData && generated.inClassQuizData.length > 0) {
              artifacts.push({
                label: 'in-class quiz',
                onClick: () => handleDownloadInClassQuiz(ch.number),
              });
            }
            if (generated.weeklyChallengeData) {
              artifacts.push(
                {
                  label: 'weekly challenge',
                  onClick: () => handleDownloadWeeklyChallenge(ch.number),
                },
                {
                  label: 'challenge SCORM',
                  onClick: () => handleDownloadWeeklyChallengeSCORM(ch.number),
                },
              );
            }
            if (generated.slidesJson) {
              artifacts.push({
                label: 'slides · pptx',
                onClick: () => handleDownloadSlides(ch.number),
              });
            }
            if (generated.audioUrl || generated.audioDataUri) {
              artifacts.push({
                label: 'audiobook · mp3',
                onClick: () => handleDownloadAudio(ch.number),
              });
            }
            if (
              (generated.discussionData && generated.discussionData.length > 0) ||
              (generated.activityData && generated.activityData.length > 0)
            ) {
              artifacts.push({
                label: 'teaching · docx',
                onClick: () => handleDownloadTeachingResources(ch.number),
              });
            }
            return (
              <ChapterRow
                key={ch.number}
                number={ch.number}
                title={ch.title}
                isComplete={isComplete}
                fileCount={chapterFileCount}
                filesPerChapter={FILES_PER_CHAPTER}
                artifacts={artifacts}
                onDownloadAll={() => void handleDownloadClassBundle(ch.number)}
              />
            );
          })}
        </section>

        {/* ── LEARNING OUTCOMES ────────────────────────────────── */}
        <LearningOutcomesPanel
          curriculumMap={curriculumMap}
          syllabus={syllabus}
          themeId={setup.themeId}
          isGenerating={isGeneratingOutcomes}
          streamChars={outcomesStreamChars}
          error={outcomesError}
          stale={outcomesStale}
          onGenerate={() => void generateLearningOutcomes()}
          onDownloadHtml={handleDownloadOutcomesHtml}
          onDownloadCsv={handleDownloadOutcomesCsv}
          canGenerate={!!claudeApiKey && !isGenerating}
        />

        <div className="cb-folio">— 05 —</div>
      </div>
    </motion.div>
  );
}

// ─── ChapterRow — generated class ────────────────────────────────────────

function ChapterRow({
  number,
  title,
  isComplete,
  fileCount,
  filesPerChapter,
  artifacts,
  onDownloadAll,
}: {
  number: number;
  title: string;
  isComplete: boolean;
  fileCount: number;
  filesPerChapter: number;
  artifacts: Array<{ label: string; onClick: () => void }>;
  onDownloadAll?: () => void;
}) {
  return (
    <article
      className="cb-artifact-row"
      style={{
        display: 'grid',
        gridTemplateColumns: '90px 1fr auto',
        alignItems: 'baseline',
        gap: 20,
        padding: '18px 0 16px',
        borderBottom: '0.5px solid var(--cb-border-default)',
      }}
    >
      <span
        className="cb-mono cb-sc"
        style={{
          fontSize: 11.5,
          letterSpacing: '0.12em',
          color: 'var(--cb-text-muted)',
        }}
      >
        Class {String(number).padStart(2, '0')}
      </span>

      <div style={{ minWidth: 0 }}>
        <h3
          className="cb-italic"
          style={{
            margin: 0,
            fontSize: 21,
            fontWeight: 500,
            lineHeight: 1.25,
            color: 'var(--cb-text-default)',
            fontVariationSettings: '"opsz" 18',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
          title={title}
        >
          {title}
        </h3>

        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 6,
            marginTop: 10,
            alignItems: 'center',
          }}
        >
          {onDownloadAll && <ClassBundleChip onClick={onDownloadAll} />}
          {artifacts.map((a) => (
            <ArtifactChip key={a.label} label={a.label} onClick={a.onClick} />
          ))}
        </div>
      </div>

      <span
        className="cb-mono"
        style={{
          fontSize: 11,
          letterSpacing: '0.06em',
          color: isComplete
            ? 'var(--cb-status-success)'
            : 'var(--cb-text-muted)',
          whiteSpace: 'nowrap',
          alignSelf: 'start',
          paddingTop: 4,
        }}
      >
        {isComplete
          ? '✓ ready'
          : `${fileCount} of ${filesPerChapter}`}
      </span>
    </article>
  );
}

// ─── ChapterRowEmpty — not yet generated ─────────────────────────────────

function ChapterRowEmpty({
  number,
  title,
  isGenerating,
  isCurrent,
  onGenerate,
}: {
  number: number;
  title: string;
  isGenerating: boolean;
  isCurrent: boolean;
  onGenerate: () => void;
}) {
  return (
    <article
      className="cb-artifact-row"
      style={{
        display: 'grid',
        gridTemplateColumns: '90px 1fr auto',
        alignItems: 'baseline',
        gap: 20,
        padding: '18px 0 16px',
        borderBottom: '0.5px solid var(--cb-border-default)',
        opacity: isCurrent ? 1 : 0.65,
      }}
    >
      <span
        className="cb-mono cb-sc"
        style={{
          fontSize: 11.5,
          letterSpacing: '0.12em',
          color: 'var(--cb-text-muted)',
        }}
      >
        Class {String(number).padStart(2, '0')}
      </span>

      <h3
        className="cb-italic"
        style={{
          margin: 0,
          fontSize: 21,
          fontWeight: 500,
          lineHeight: 1.25,
          color: 'var(--cb-text-muted)',
          fontVariationSettings: '"opsz" 18',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        }}
        title={title}
      >
        {title}
      </h3>

      {isCurrent ? (
        <span
          className="cb-italic"
          style={{
            fontSize: 13,
            color: 'var(--cb-accent-emphasis)',
            whiteSpace: 'nowrap',
          }}
        >
          drafting…
        </span>
      ) : (
        <Button
          size="sm"
          variant="ghost"
          onClick={onGenerate}
          disabled={isGenerating}
        >
          Draft class ↓
        </Button>
      )}
    </article>
  );
}

// ─── ArtifactChip — single download affordance ───────────────────────────

function ArtifactChip({ label, onClick }: { label: string; onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="cb-mono cb-focus"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        background: 'transparent',
        border: '0.5px solid var(--cb-border-default)',
        borderRadius: 1.5,
        padding: '4px 9px 5px',
        fontSize: 10.5,
        letterSpacing: '0.1em',
        color: 'var(--cb-text-muted)',
        cursor: 'pointer',
        textTransform: 'lowercase',
        fontFamily: 'var(--font-cb-mono)',
        transition:
          'border-color 160ms ease, color 160ms ease, background 160ms ease',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = 'var(--cb-accent-emphasis)';
        e.currentTarget.style.color = 'var(--cb-accent-emphasis)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'var(--cb-border-default)';
        e.currentTarget.style.color = 'var(--cb-text-muted)';
      }}
    >
      {label}
      <span aria-hidden style={{ fontSize: 10, opacity: 0.65 }}>↓</span>
    </button>
  );
}

// ─── ClassBundleChip — primary "download everything for this class" ──────
//
// Visually distinct from the per-artifact chips: filled accent background,
// inverse text, sits at the start of the chip row so it reads as the primary
// action. The lowercase "class · zip" label follows the same monospace voice
// as the artifact chips, just inverted in colour.

function ClassBundleChip({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="cb-mono cb-focus"
      title="Download every generated artefact for this class as a single ZIP"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 7,
        background: 'var(--cb-accent-emphasis)',
        border: '0.5px solid var(--cb-accent-emphasis)',
        borderRadius: 1.5,
        padding: '5px 11px 6px',
        fontSize: 10.5,
        letterSpacing: '0.12em',
        color: '#fff',
        cursor: 'pointer',
        textTransform: 'lowercase',
        fontFamily: 'var(--font-cb-mono)',
        fontWeight: 500,
        transition: 'background-color 160ms ease, transform 160ms ease',
        boxShadow: '0 1px 0 rgba(20,17,13,0.06)',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.transform = 'translateY(-1px)';
        e.currentTarget.style.boxShadow = '0 2px 6px rgba(110,31,36,0.22)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = 'translateY(0)';
        e.currentTarget.style.boxShadow = '0 1px 0 rgba(20,17,13,0.06)';
      }}
    >
      <span aria-hidden style={{ fontSize: 11, lineHeight: 1, opacity: 0.85 }}>⎙</span>
      class · zip
      <span aria-hidden style={{ fontSize: 10, opacity: 0.85 }}>↓</span>
    </button>
  );
}

// ─── LearningOutcomesPanel ───────────────────────────────────────────────

function LearningOutcomesPanel(props: {
  curriculumMap: import('../types/course').CurriculumMap | null;
  syllabus: import('../types/course').Syllabus;
  themeId?: string;
  isGenerating: boolean;
  streamChars: number;
  error: string | null;
  stale: boolean;
  canGenerate: boolean;
  onGenerate: () => void;
  onDownloadHtml: () => void;
  onDownloadCsv: () => void;
}) {
  const {
    curriculumMap,
    syllabus,
    themeId,
    isGenerating,
    streamChars,
    error,
    stale,
    canGenerate,
    onGenerate,
    onDownloadHtml,
    onDownloadCsv,
  } = props;

  const tableSrcDoc = useMemo(() => {
    if (!curriculumMap) return null;
    const fragment = buildOutcomesTableFragment(curriculumMap, syllabus, themeId);
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600&family=Manrope:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Serif:wght@400;600&family=IBM+Plex+Sans:wght@400;500;600&family=Lora:wght@400;500;600&family=Libre+Caslon+Text:wght@400;700&family=Cormorant+Garamond:wght@400;500;600&family=DM+Serif+Display&family=Instrument+Serif&family=JetBrains+Mono:wght@400;500;600;700&display=swap"><style>html,body{margin:0;padding:0;}</style></head><body>${fragment}</body></html>`;
  }, [curriculumMap, syllabus, themeId]);

  return (
    <section
      style={{
        marginBottom: 36,
        padding: '22px 24px 24px',
        border: '0.5px solid var(--cb-border-default)',
        background: 'var(--cb-ground-canvas)',
        borderRadius: 3,
      }}
    >
      {/* Header strip */}
      <div
        style={{
          display: 'flex',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
          gap: 18,
          flexWrap: 'wrap',
          marginBottom: curriculumMap ? 14 : 8,
        }}
      >
        <div style={{ minWidth: 0, flex: '1 1 320px' }}>
          <div
            className="cb-sc"
            style={{
              fontSize: 11.5,
              letterSpacing: '0.14em',
              color: 'var(--cb-text-muted)',
              marginBottom: 5,
            }}
          >
            Learning outcomes
          </div>
          {curriculumMap ? (
            <p
              className="cb-italic"
              style={{
                margin: 0,
                fontSize: 14.5,
                color: 'var(--cb-text-muted)',
                lineHeight: 1.5,
              }}
            >
              {curriculumMap.objectives.length} measurable objectives mapped to{' '}
              {syllabus.chapters.length}{' '}
              {syllabus.chapters.length === 1 ? 'chapter' : 'chapters'} ·
              Introduced, Developed, Mastered.
            </p>
          ) : (
            <p
              style={{
                margin: 0,
                fontSize: 14.5,
                color: 'var(--cb-text-default)',
                lineHeight: 1.55,
                maxWidth: '60ch',
              }}
            >
              A measurable list of what students will know and be able to do,
              mapped to where each objective is{' '}
              <span className="cb-italic">Introduced</span>,{' '}
              <span className="cb-italic">Developed</span>, and{' '}
              <span className="cb-italic">Mastered</span> across your chapters.
              Used by most universities for course accreditation.
            </p>
          )}
        </div>

        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          {curriculumMap && !isGenerating && (
            <>
              <Button size="sm" variant="ghost" onClick={onDownloadCsv}>
                Download CSV ↓
              </Button>
              <Button size="sm" variant="secondary" onClick={onDownloadHtml}>
                Download HTML ↓
              </Button>
              <Button
                size="sm"
                variant={stale ? 'primary' : 'ghost'}
                onClick={onGenerate}
                disabled={!canGenerate}
                title={!canGenerate ? 'Add a Claude API key to regenerate.' : undefined}
              >
                {stale ? 'Regenerate ↻' : 'Regenerate'}
              </Button>
            </>
          )}
          {!curriculumMap && !isGenerating && (
            <Button
              size="sm"
              variant="primary"
              onClick={onGenerate}
              disabled={!canGenerate}
              title={!canGenerate ? 'Add a Claude API key in Setup to generate.' : undefined}
            >
              Generate learning outcomes →
            </Button>
          )}
        </div>
      </div>

      {/* Stale banner */}
      {curriculumMap && stale && !isGenerating && (
        <div
          style={{
            marginTop: 4,
            marginBottom: 14,
            padding: '10px 14px',
            background: 'var(--cb-status-warning-bg, rgba(207, 134, 35, 0.08))',
            borderLeft: '2px solid var(--cb-status-warning, #cf8623)',
            fontSize: 13.5,
            color: 'var(--cb-text-default)',
            lineHeight: 1.55,
          }}
        >
          <strong style={{ fontWeight: 600 }}>Out of date.</strong>{' '}
          The syllabus has been revised since these outcomes were generated{' '}
          {curriculumMap.generatedAt ? `on ${new Date(curriculumMap.generatedAt).toLocaleDateString()}` : ''}.
          Regenerate to align them with the current chapter set.
        </div>
      )}

      {/* Streaming state */}
      {isGenerating && (
        <div
          style={{
            marginTop: 10,
            padding: '14px 16px',
            border: '0.5px dashed var(--cb-border-default)',
            background: 'var(--cb-ground-page)',
            borderRadius: 3,
            display: 'flex',
            alignItems: 'baseline',
            gap: 12,
          }}
        >
          <span
            aria-hidden
            style={{
              display: 'inline-block',
              width: 44,
              height: 1,
              background: 'var(--cb-border-default)',
              position: 'relative',
              overflow: 'hidden',
              verticalAlign: 'middle',
            }}
          >
            <span
              style={{
                position: 'absolute',
                inset: 0,
                background: 'var(--cb-accent-emphasis)',
                animation: 'cb-pen 1.4s cubic-bezier(0.32,0.04,0.32,1) infinite',
              }}
            />
          </span>
          <span
            className="cb-italic"
            style={{ fontSize: 14.5, color: 'var(--cb-text-muted)', lineHeight: 1.5 }}
          >
            Drafting learning outcomes · {streamChars.toLocaleString()} characters streamed…
          </span>
        </div>
      )}

      {/* Error */}
      {error && !isGenerating && (
        <div
          style={{
            marginTop: 10,
            padding: '10px 14px',
            background: 'var(--cb-status-danger-bg, rgba(160, 53, 53, 0.08))',
            borderLeft: '2px solid var(--cb-status-danger, #a03535)',
            fontSize: 13.5,
            color: 'var(--cb-text-default)',
            lineHeight: 1.55,
          }}
        >
          {error}
        </div>
      )}

      {/* Preview iframe */}
      {tableSrcDoc && !isGenerating && (
        <div
          style={{
            marginTop: 12,
            border: '0.5px solid var(--cb-border-default)',
            borderRadius: 3,
            overflow: 'hidden',
            background: '#fff',
          }}
        >
          <iframe
            srcDoc={tableSrcDoc}
            sandbox="allow-same-origin"
            title="Learning outcomes preview"
            style={{
              width: '100%',
              border: 'none',
              minHeight: 520,
              display: 'block',
            }}
          />
        </div>
      )}
    </section>
  );
}
